# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties
#   check these on https://fabricmc.net/develop
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.17.2

# Mod Properties
mod_version=0.1.0
maven_group=com.aaroncraft.megacobble
archives_base_name=megacobble

# Dependencies
#   Fabric API: https://github.com/FabricMC/fabric/releases
fabric_version=0.116.6+1.21.1
#   Cobblemon: https://maven.impactdev.net/#/development/com/cobblemon/fabric
cobblemon_version=1.7.3+1.21.1
#   Fabric Language Kotlin (Cobblemon is written in Kotlin and requires this at runtime)
fabric_kotlin_version=1.12.3+kotlin.2.0.21
